# Resource-1: Azure Resource Group

resource "azurerm_resource_group" "myrg1" 
{
  name = "myrg-1"
  location = "East US"
}

# Resource-2: Random String 

resource "random_string" "myrandom" 
{
  length = 16
  upper = false 
  special = false
}

# Resource-3: Azure Storage Account 
resource "azurerm_storage_account" "mysa" 
{
  name                     = "mysa${random_string.myrandom.id}"
  resource_group_name      = azurerm_resource_group.myrg1.name
  location                 = azurerm_resource_group.myrg1.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
  account_encryption_source = "Microsoft.Storage"

  tags = {
    environment = "staging"
  }
}

-----------------------------------------------------------------------------------------------------------------------

# Explanation: - 

This code snippet represents a Terraform configuration that defines three resources: an Azure Resource Group, a Random String, and an Azure Storage Account. Below is a detailed explanation of each resource and its components:

### 1. Resource-1: Azure Resource Group


resource "azurerm_resource_group" "myrg1" {
  name = "myrg-1"
  location = "East US"
}

- Resource Type: azurerm_resource_group is the resource type for creating a resource group in Azure.

- Resource Name: "myrg1" is the identifier for this specific resource within the configuration. This name is used to reference the resource elsewhere in the configuration.

- Attributes:

- name: Specifies the name of the resource group, set to "myrg-1".
- location: Specifies the Azure region where the resource group is created, set to "East US".

Explanation: An Azure Resource Group is a logical container in Azure that holds related resources for an Azure solution. This block creates a resource group named myrg-1 in the East US region.

### 2. Resource-2: Random String

resource "random_string" "myrandom" {
  length = 16
  upper = false 
  special = false
}

- Resource Type: random_string is used to create a random string resource.

- Resource Name: "myrandom" is the identifier for this resource.

- Attributes:

- length: Sets the length of the generated string to 16 characters.
- upper: Specifies whether uppercase letters are included. false means only lowercase letters and numbers are used.
- special: Specifies whether special characters are included. false means no special characters are in the generated string.

Explanation: This block generates a random string that can be used for resource names or other purposes. In this configuration, it is used for the name of the Azure Storage Account.

### 3. Resource-3: Azure Storage Account

resource "azurerm_storage_account" "mysa" {
  name                     = "mysa${random_string.myrandom.id}"
  resource_group_name      = azurerm_resource_group.myrg1.name
  location                 = azurerm_resource_group.myrg1.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
  account_encryption_source = "Microsoft.Storage"

  tags = {
    environment = "staging"
  }
}

- Resource Type: azurerm_storage_account is used to create an Azure Storage Account.

- Resource Name: "mysa" is the identifier for this resource.

- Attributes:

- name: The name of the storage account. The name is set to "mysa" followed by the random string generated by random_string.myrandom.id. This makes the name unique.
- resource_group_name: Specifies the name of the resource group to which the storage account belongs. This references the name attribute from azurerm_resource_group.myrg1.
- location: Specifies the Azure region where the storage account is created. It references the location from azurerm_resource_group.myrg1.
- account_tier: Defines the performance tier of the storage account. "Standard" is chosen for cost-effective storage.
- account_replication_type: Specifies the type of replication. "GRS" stands for **Geo-Redundant Storage**, which provides high availability by replicating data to a secondary region.
- account_encryption_source: Specifies the encryption source, set to "Microsoft.Storage", which uses Azure's managed keys for encryption.

- Tags:

- tags: Metadata added to the resource for identification. Here, a tag with environment = "staging" is added, which helps in categorizing and managing resources.

Explanation: This block defines an Azure Storage Account with a unique name using the random string generated by the random_string resource. It is placed in the myrg-1 resource group in the East US, uses Standard performance, and is set for GRS replication, ensuring resilience and high availability.

### Summary

- Resource 1 creates an Azure Resource Group named myrg-1.
- Resource 2 generates a random 16-character string for use in naming.
- Resource 3 creates an Azure Storage Account with a unique name formed by appending the random string, configured with Standard tier, GRS replication, and basic encryption settings. The resources are interconnected using references to ensure consistency and reusability.
